name: Generate PDFs for Release

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Convert Instructor Quick Start Guide
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs/Instructor_Quick_Start_Guide.md
      
      - name: Convert Instructor Reference Guide
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs/Instructor_Reference_Guide.md
      
      - name: Convert Student Quick Start Guide
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs/Student_Quick_Start_Guide.md
      
      - name: Convert What's New
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs/WHATS_NEW_v1.6.0.md
      
      - name: Convert README
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
      
      - name: Collect and rename PDFs
        run: |
          mkdir -p docs/pdf
          # The markdown-to-pdf action creates files with "built" prefix in various locations
          # Find all built PDFs and move/rename them
          find . -name "built*.pdf" -o -name "*built*.pdf" | while read pdf; do
            # Extract the base filename without "built" prefix
            basename=$(basename "$pdf" | sed 's/^built//')
            mv "$pdf" "docs/pdf/$basename"
            echo "Moved $pdf -> docs/pdf/$basename"
          done
          # Also move README.pdf if it exists
          find . -maxdepth 2 -name "README.pdf" -not -path "./docs/pdf/*" -exec mv {} docs/pdf/ \; 2>/dev/null || true
          echo "\nFinal PDFs in docs/pdf/:"
          ls -lh docs/pdf/*.pdf 2>/dev/null || echo "No PDFs found"
      
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdfs
          path: docs/pdf/*.pdf
      
      - name: Attach PDFs to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: docs/pdf/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
