name: Lint Prompts
on: [pull_request]
jobs:
  lint-prompts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run linter (fail on changes)
        run: |
          bash tools/lint_ci.sh --root .
